Fix r2-v script

diff --git a/r2-v b/r2-v
--- a/r2-v
+++ b/r2-v
@@ -1,21 +1,28 @@
 #!/bin/sh
-MASTER=/home/maijin/radare2/
+if [ -z "${R2_MASTER}" ]; then
+	R2_MASTER=~/radare2/
+fi
 COPIES=~/prg/r2-v
+
+if [ ! -d "${R2_MASTER}" ]; then
+	echo "Cannot find master copy of r2 at R2_MASTER=${R2_MASTER}"
+	exit 1
+fi
 
 mkdir -p ${COPIES}
 
 Head() {
-	cd ${MASTER}
+	cd ${R2_MASTER}
 	git rev-list HEAD |head -n1
 }
 
 Next() {
-	cd ${MASTER}
+	cd ${R2_MASTER}
 	git rev-list HEAD | grep -C 1 $1 |head -n1
 }
 
 Prev() {
-	cd ${MASTER}
+	cd ${R2_MASTER}
 	git rev-list HEAD | grep -C 1 $1 |tail -n1
 }
 
@@ -43,7 +50,11 @@ Clone() {
 	cd ${COPIES}
 	if [ ! -d ${COPIES}/radare2-${1} ]; then
 		echo "$1  git clone"
-		git clone ${MASTER} radare2-${1} > /dev/null 2>&1
+		git clone ${R2_MASTER} radare2-${1} > /dev/null 2>&1
+	fi
+	if [ ! -d ${COPIES}/radare2-${1} ]; then
+		echo "Cant clone"
+		exit 1
 	fi
 	cd radare2-${1}
 	if [ -d .git ]; then
@@ -64,7 +75,7 @@ init)
 	Clone `Head`
 	;;
 log)
-	cd ${MASTER}
+	cd ${R2_MASTER}
 	cur=`Cur`
 	for a in `git rev-list HEAD` ; do
 		NOTE=`cat ${COPIES}/radare2-${a}.note 2>/dev/null`
@@ -123,7 +134,7 @@ note)
 	Note $2 $3
 	;;
 diff)
-	cd ${MASTER}
+	cd ${R2_MASTER}
 	git diff `Cur`^..`Cur`
 	;;
 use)
