Update r2-v
pr for #2448

diff --git a/r2-v b/r2-v
--- a/r2-v
+++ b/r2-v
@@ -1,33 +1,42 @@
 #!/bin/sh
-if [ -z "${R2_MASTER}" ]; then
+if test -z "${R2_MASTER}"; then
 	R2_MASTER=~/radare2/
 fi
 COPIES=~/prg/r2-v
 
-if [ ! -d "${R2_MASTER}" ]; then
+if  ! test -d "${R2_MASTER}"; then
 	echo "Cannot find master copy of r2 at R2_MASTER=${R2_MASTER}"
 	exit 1
 fi
 
-mkdir -p ${COPIES}
+
+if ! mkdir -p "${COPIES}"; then
+   echo "Cannot create COPIES=${COPIES}"
+   exit 1
+fi
+
+Fail() {
+ printf "%s" "$1\n"
+ exit 1 
+}
 
 Head() {
-	cd ${R2_MASTER}
-	git rev-list HEAD |head -n1
+	cd ${R2_MASTER}   || Fail "cannot chdir to ${R2_MASTER}" 
+	git rev-list HEAD |  head -n1
 }
 
 Next() {
-	cd ${R2_MASTER}
+	cd ${R2_MASTER}   || Fail "cannot chdir to ${R2_MASTER}" 
 	git rev-list HEAD | grep -C 1 $1 |head -n1
 }
 
 Prev() {
-	cd ${R2_MASTER}
+	cd ${R2_MASTER}   || Fail "cannot chdir to ${R2_MASTER}"
 	git rev-list HEAD | grep -C 1 $1 |tail -n1
 }
 
 Cur() {
-	if [ -f ${COPIES}/cur ]; then
+	if test -f ${COPIES}/cur; then
 		cat ${COPIES}/cur
 	else
 		echo "Run init first"
@@ -35,8 +44,8 @@ Cur() {
 }
 
 Note() {
-	if [ -n "$1" ]; then
-		if [ -n "$2" ]; then
+	if test -n "$1"; then
+		if test -n "$2"; then
 			echo "$2" > ${COPIES}/radare2-$1.note
 		else
 			cat ${COPIES}/radare2-$1.note
@@ -47,7 +56,7 @@ Note() {
 }
 
 Clone() {
-	cd ${COPIES}
+	cd ${COPIES} || exit 1
 	if [ ! -d ${COPIES}/radare2-${1} ]; then
 		echo "$1  git clone"
 		git clone ${R2_MASTER} radare2-${1} > /dev/null 2>&1
@@ -75,7 +84,7 @@ init)
 	Clone `Head`
 	;;
 log)
-	cd ${R2_MASTER}
+	cd ${R2_MASTER} || Fail "cannot chdir to ${R2_MASTER}" 
 	cur=`Cur`
 	for a in `git rev-list HEAD` ; do
 		NOTE=`cat ${COPIES}/radare2-${a}.note 2>/dev/null`
@@ -134,7 +143,7 @@ note)
 	Note $2 $3
 	;;
 diff)
-	cd ${R2_MASTER}
+	cd ${R2_MASTER} || Fail "cannot chdir to ${R2_MASTER}" 
 	git diff `Cur`^..`Cur`
 	;;
 use)
